-- Chạy toàn bộ đoạn SQL này trong Supabase SQL Editor.
create table if not exists public.meal_registrations (
  id bigint generated by default as identity primary key,
  name text not null,
  meal_date date not null,
  meal text not null check (meal in ('Trưa','Tối')),
  time_type text not null check (time_type in ('Đúng giờ','Ăn trễ')),
  quantity integer not null check (quantity between 1 and 20),
  note text,
  created_at timestamptz not null default now()
);

alter table public.meal_registrations enable row level security;

-- Cho phép khách truy cập website xem danh sách.
create policy "public can read meal registrations"
on public.meal_registrations
for select
to anon
using (true);

-- Cho phép khách truy cập website đăng ký.
create policy "public can insert meal registrations"
on public.meal_registrations
for insert
to anon
with check (true);

-- KHÔNG bật policy DELETE cho anon.
-- Việc xóa nên làm trong Supabase Dashboard/admin sau này.
