-- PHIÊN BẢN MỚI: đăng nhập Google + RLS + khóa thời gian ở DATABASE.
-- Chạy toàn bộ file này trong Supabase SQL Editor.
-- Nếu đang dùng bảng cũ của bản demo trước, lệnh DROP bên dưới sẽ xóa dữ liệu demo đó.

drop table if exists public.meal_registrations;

create table public.meal_registrations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  name text not null,
  meal_date date not null,
  meal text not null check (meal in ('Trưa','Tối')),
  status text not null check (status in ('Đúng giờ','Ăn trễ','Không ăn')),
  created_at timestamptz not null default now(),
  unique(user_id, meal_date, meal)
);

alter table public.meal_registrations enable row level security;

create policy "authenticated can read registrations"
on public.meal_registrations for select
to authenticated using (true);

create policy "users can insert their own registration"
on public.meal_registrations for insert
to authenticated
with check (auth.uid() = user_id);

create policy "users can update their own registration"
on public.meal_registrations for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Không cho xóa để tránh làm sai số liệu tổng kết.
-- Nếu muốn cho phép xóa, có thể thêm policy sau này.

create or replace function public.check_meal_time_rules()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  vn_time time;
  vn_date date;
begin
  vn_time := (now() at time zone 'Asia/Ho_Chi_Minh')::time;
  vn_date := (now() at time zone 'Asia/Ho_Chi_Minh')::date;

  if tg_op = 'INSERT' then
    -- Với suất của hôm nay: hết 08:00 thì không nhận đăng ký mới.
    if new.meal_date = vn_date and vn_time >= time '08:00' then
      raise exception 'Đã quá 08:00, không thể đăng ký mới cho hôm nay.';
    end if;
    if new.meal_date < vn_date then
      raise exception 'Không thể đăng ký ngày đã qua.';
    end if;
  end if;

  if tg_op = 'UPDATE' then
    -- Chỉ được đổi trạng thái Đúng giờ <-> Ăn trễ, không đổi sang Không ăn.
    if new.status = 'Không ăn' then
      raise exception 'Không thể đổi sang Không ăn sau khi đã đăng ký.';
    end if;

    if new.status not in ('Đúng giờ','Ăn trễ') then
      raise exception 'Trạng thái không hợp lệ.';
    end if;

    if new.meal_date <> vn_date then
      raise exception 'Chỉ được thay đổi trạng thái cho suất của hôm nay.';
    end if;

    if new.meal = 'Trưa' then
      if vn_time >= time '10:30' then
        raise exception 'Đã quá 10:30, không thể đổi trạng thái suất trưa.';
      end if;
    elsif new.meal = 'Tối' then
      if vn_time >= time '17:30' then
        raise exception 'Đã quá 17:30, không thể đổi trạng thái suất tối.';
      end if;
    end if;
  end if;

  return new;
end;
$$;

create trigger meal_time_rules
before insert or update on public.meal_registrations
for each row execute function public.check_meal_time_rules();
